server:
  port: 8701
spring:
    application:
    name: delivery-merchant-service
    datasource:
        name: delivery
        url: jdbc:mysql://localhost:3306/delivery?serverTimezone=CTT&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.twoyum.authority.model
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql